name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install QPM
        run: |
          curl -Lo qpm https://github.com/sc2ad/QuestPackageManager/releases/latest/download/qpm-linux-x64
          chmod +x qpm
          sudo mv qpm /usr/local/bin/

      - name: QPM Restore
        run: qpm restore

      - name: Build
        run: |
          mkdir build 
          cd build 
          cmake .. 
          make
